<template>
  <div class="operaciones-page">
    <v-card class="operaciones-header mb-5 rounded-xl" elevation="0" border><v-card-text class="pa-5"><div class="d-flex align-center flex-wrap ga-3"><v-avatar color="primary" variant="tonal" size="48" rounded="lg"><v-icon size="27">mdi-cash-register</v-icon></v-avatar><div><div class="text-h6 font-weight-bold">Control de caja</div><div class="text-body-2 text-medium-emphasis">Apertura, saldos por medio de pago y cierre diario</div></div><v-spacer/><v-chip color="primary" variant="tonal">{{ branch.sucursalActual?.nombre || 'Sin sucursal' }}</v-chip><v-btn v-if="canManage&&branch.idSucursalActual&&!openBox" color="primary" prepend-icon="mdi-lock-open-variant-outline" rounded="lg" @click="openOpenDialog">Abrir caja</v-btn><v-btn v-if="canManage&&openBox" color="error" variant="tonal" prepend-icon="mdi-lock-outline" rounded="lg" @click="openCloseDialog">Cerrar caja</v-btn></div></v-card-text></v-card>
    <v-alert v-if="error" type="error" variant="tonal" closable class="mb-4" @click:close="error=''">{{ error }}</v-alert>
    <v-alert v-if="!branch.idSucursalActual" type="info" variant="tonal" class="mb-4">Selecciona una sucursal para consultar la caja.</v-alert>
    <template v-else>
      <v-row class="mb-3"><v-col cols="12" md="4"><v-card class="operaciones-metric rounded-xl" border elevation="0"><v-card-text><div class="text-caption text-medium-emphasis">Estado actual</div><div class="d-flex align-center mt-2"><v-icon :color="openBox?'success':'medium-emphasis'" size="32">{{ openBox?'mdi-lock-open-check-outline':'mdi-lock-outline' }}</v-icon><div class="text-h6 font-weight-bold ms-3">{{ openBox?'Caja abierta':'Caja cerrada' }}</div></div></v-card-text></v-card></v-col><v-col cols="12" md="4"><v-card class="operaciones-metric rounded-xl" border elevation="0"><v-card-text><div class="text-caption text-medium-emphasis">Saldo esperado</div><div class="text-h5 font-weight-bold money mt-2">{{ money(expectedTotal) }}</div></v-card-text></v-card></v-col><v-col cols="12" md="4"><v-card class="operaciones-metric rounded-xl" border elevation="0"><v-card-text><div class="text-caption text-medium-emphasis">Apertura</div><div class="text-h5 font-weight-bold money mt-2">{{ money(openBox?.montoApertura) }}</div></v-card-text></v-card></v-col></v-row>
      <v-card v-if="openBox" rounded="xl" elevation="0" border class="mb-5"><v-card-title class="pa-5 pb-2 d-flex align-center"><v-icon color="primary" class="me-2">mdi-wallet-outline</v-icon>Saldos por medio de pago<v-spacer/><span class="text-caption text-medium-emphasis">Abierta {{ dateTime(openBox.fechaApertura) }}</span></v-card-title><v-card-text class="pa-5"><v-row><v-col v-for="detail in openBox.detalles" :key="detail.idMedioPago" cols="12" sm="6" md="4"><v-card variant="tonal" color="primary" rounded="lg"><v-card-text class="d-flex align-center"><v-icon size="28">mdi-credit-card-outline</v-icon><div class="ms-3"><div class="text-caption">{{ detail.medioPago.nombre }}</div><div class="text-h6 font-weight-bold money">{{ money(detail.monto) }}</div></div></v-card-text></v-card></v-col><v-col v-if="!openBox.detalles.length" cols="12"><div class="text-center text-medium-emphasis py-4">La caja no tiene saldos distribuidos.</div></v-col></v-row></v-card-text></v-card>
      <v-card rounded="xl" elevation="0" border class="overflow-hidden"><div class="pa-4 operaciones-toolbar"><div class="text-subtitle-1 font-weight-bold">Historial de cajas</div><v-spacer/><v-btn icon="mdi-refresh" variant="tonal" color="primary" :loading="loading" @click="load"/></div><v-divider/><div v-if="loading" class="text-center py-14"><v-progress-circular indeterminate color="primary"/></div><template v-else-if="items.length"><v-table hover class="operaciones-table operaciones-desktop"><thead><tr><th>N.º</th><th>Apertura</th><th>Cierre</th><th>Responsable</th><th>Estado</th><th class="text-end">Monto apertura</th></tr></thead><tbody><tr v-for="item in items" :key="item.idCaja"><td>#{{ item.idCaja }}</td><td>{{ dateTime(item.fechaApertura) }}</td><td>{{ dateTime(item.fechaCierre) }}</td><td>{{ user(item.usuarioApertura) }}</td><td><v-chip size="small" :color="item.fechaCierre?'default':'success'" variant="tonal">{{ item.fechaCierre?'Cerrada':'Abierta' }}</v-chip></td><td class="text-end money">{{ money(item.montoApertura) }}</td></tr></tbody></v-table><div class="operaciones-mobile pa-3"><v-card v-for="item in items" :key="item.idCaja" variant="outlined" rounded="lg" class="mb-3"><v-card-text><div class="d-flex"><strong>Caja #{{ item.idCaja }}</strong><v-spacer/><v-chip size="x-small" :color="item.fechaCierre?'default':'success'">{{ item.fechaCierre?'Cerrada':'Abierta' }}</v-chip></div><div class="text-caption text-medium-emphasis mt-2">{{ dateTime(item.fechaApertura) }} · {{ user(item.usuarioApertura) }}</div><div class="font-weight-bold money mt-2">{{ money(item.montoApertura) }}</div></v-card-text></v-card></div></template><div v-else class="operaciones-empty"><v-icon size="48">mdi-cash-register</v-icon><div class="mt-2">Aún no hay cajas registradas</div></div><v-divider/><div class="d-flex align-center justify-space-between pa-3"><span class="text-caption">Mostrando {{ items.length }} de {{ total }}</span><v-pagination v-if="total>limit" v-model="page" :length="Math.ceil(total/limit)" size="small"/></div></v-card>
    </template>

    <v-dialog v-model="openDialog" max-width="650" persistent><v-card rounded="xl"><v-card-title class="operaciones-dialog-title"><span class="operaciones-dialog-icon"><v-icon>mdi-lock-open-variant-outline</v-icon></span>Abrir caja<v-spacer/><v-btn icon="mdi-close" variant="text" color="on-primary" @click="openDialog=false"/></v-card-title><v-card-text class="pa-5"><v-alert v-if="formError" type="error" variant="tonal" class="mb-4">{{ formError }}</v-alert><label class="operaciones-field-label">Monto inicial</label><v-text-field v-model="openingAmount" prefix="S/" type="number" min="0" step="0.01" variant="outlined" @update:model-value="syncOpeningPayment"/><PagosEditor v-model="openingPayments" :medios="paymentMethods"/></v-card-text><v-divider/><v-card-actions class="pa-4"><v-spacer/><v-btn variant="text" @click="openDialog=false">Cancelar</v-btn><v-btn color="primary" :loading="saving" @click="openCash">Abrir caja</v-btn></v-card-actions></v-card></v-dialog>
    <v-dialog v-model="closeDialog" max-width="520" persistent><v-card rounded="xl"><v-card-title class="operaciones-dialog-title"><span class="operaciones-dialog-icon"><v-icon>mdi-lock-outline</v-icon></span>Cerrar caja</v-card-title><v-card-text class="pa-5"><v-alert v-if="formError" type="error" variant="tonal" class="mb-4">{{ formError }}</v-alert><div class="text-body-2 text-medium-emphasis mb-3">Saldo esperado: <strong>{{ money(expectedTotal) }}</strong></div><label class="operaciones-field-label">Monto contado *</label><v-text-field v-model="closingAmount" prefix="S/" type="number" min="0" step="0.01" variant="outlined" autofocus/><v-alert type="warning" variant="tonal" density="compact">El cierre es definitivo y conservará cualquier diferencia de caja.</v-alert></v-card-text><v-card-actions class="pa-4"><v-spacer/><v-btn variant="text" @click="closeDialog=false">Cancelar</v-btn><v-btn color="error" :loading="saving" @click="closeCash">Confirmar cierre</v-btn></v-card-actions></v-card></v-dialog>
    <v-snackbar v-model="noticeVisible" color="success">{{ notice }}</v-snackbar>
  </div>
</template>
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { getApiErrorMessage } from '@/core/api/api-error'
import { mediosPagoApi } from '@/core/api/administracion.api'
import { Permiso } from '@/core/constants/permisos'
import type { MedioPago } from '@/core/types/administracion.types'
import { useAuthStore } from '@/modules/auth/auth.store'
import { useSucursalStore } from '@/shared/stores/sucursal.store'
import PagosEditor from '../components/PagosEditor.vue'
import { cajasApi } from '../operaciones.api'
import type { Caja, PagoPayload, UsuarioResumen } from '../operaciones.types'
import '../operaciones.css'
const auth=useAuthStore(),branch=useSucursalStore(),canManage=computed(()=>auth.puede(Permiso.CAJA_GESTIONAR))
const openBox=ref<Caja|null>(null),items=ref<Caja[]>([]),paymentMethods=ref<MedioPago[]>([]),loading=ref(false),saving=ref(false),error=ref(''),formError=ref(''),openDialog=ref(false),closeDialog=ref(false),openingAmount=ref('0.00'),closingAmount=ref(''),openingPayments=ref<PagoPayload[]>([]),page=ref(1),total=ref(0),limit=20,notice=ref(''),noticeVisible=ref(false)
const expectedTotal=computed(()=>openBox.value?.detalles.reduce((sum,x)=>sum+Number(x.monto),0)??0)
async function load(){if(!branch.idSucursalActual){openBox.value=null;items.value=[];return}loading.value=true;error.value='';try{const [history,methods]=await Promise.all([cajasApi.listar({idSucursal:branch.idSucursalActual,pagina:page.value,limite:limit}),mediosPagoApi.listar()]);items.value=history.data.data;total.value=history.data.total;paymentMethods.value=methods.data.filter(x=>x.nombre.toLowerCase()!=='fraccionado');try{openBox.value=(await cajasApi.abierta(branch.idSucursalActual)).data}catch{openBox.value=null}}catch(cause){error.value=getApiErrorMessage(cause,'No se pudo cargar la caja')}finally{loading.value=false}}
function openOpenDialog(){openingAmount.value='0.00';openingPayments.value=[];formError.value='';openDialog.value=true}
function syncOpeningPayment(){if(openingPayments.value.length===1)openingPayments.value=[{...openingPayments.value[0]!,monto:openingAmount.value}]}
async function openCash(){if(!branch.idSucursalActual)return;const amount=Number(openingAmount.value);if(!Number.isFinite(amount)||amount<0){formError.value='Ingresa un monto inicial válido';return}if(Math.abs(openingPayments.value.reduce((s,x)=>s+Number(x.monto||0),0)-amount)>.001){formError.value='La suma por medios debe coincidir con el monto inicial';return}saving.value=true;formError.value='';try{await cajasApi.abrir({idSucursal:branch.idSucursalActual,montoApertura:amount.toFixed(2),detalles:openingPayments.value});openDialog.value=false;notice.value='Caja abierta correctamente';noticeVisible.value=true;await load()}catch(cause){formError.value=getApiErrorMessage(cause,'No se pudo abrir la caja')}finally{saving.value=false}}
function openCloseDialog(){closingAmount.value=expectedTotal.value.toFixed(2);formError.value='';closeDialog.value=true}
async function closeCash(){if(!openBox.value)return;const amount=Number(closingAmount.value);if(!Number.isFinite(amount)||amount<0){formError.value='Ingresa el monto contado';return}saving.value=true;try{await cajasApi.cerrar(openBox.value.idCaja,amount.toFixed(2));closeDialog.value=false;notice.value='Caja cerrada correctamente';noticeVisible.value=true;await load()}catch(cause){formError.value=getApiErrorMessage(cause,'No se pudo cerrar la caja')}finally{saving.value=false}}
function money(value:string|number|null|undefined){return new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(value)||0)}
function dateTime(value:string|null){return value?new Intl.DateTimeFormat('es-PE',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—'}
function user(value:UsuarioResumen){return value.perfil?`${value.perfil.nombres} ${value.perfil.apellidos}`:value.correo}
watch([()=>branch.idSucursalActual,page],load,{immediate:true})
</script>
