<template>
  <div class="operaciones-page">
    <v-card class="operaciones-header mb-5 rounded-xl" elevation="0" border><v-card-text class="pa-5"><div class="d-flex align-center ga-3"><v-avatar color="primary" variant="tonal" size="48" rounded="lg"><v-icon size="28">mdi-format-list-bulleted-type</v-icon></v-avatar><div><div class="text-h6 font-weight-bold">Catálogos operativos</div><div class="text-body-2 text-medium-emphasis">Motivos de caja y tipos de comprobante</div></div></div></v-card-text></v-card>
    <v-alert v-if="error" type="error" variant="tonal" closable class="mb-4" @click:close="error=''">{{ error }}</v-alert>
    <v-card rounded="xl" elevation="0" border><v-tabs v-model="tab" color="primary" grow><v-tab v-if="canSeeCash" value="income"><v-icon class="me-2">mdi-cash-plus</v-icon>Motivos de ingreso</v-tab><v-tab v-if="canSeeCash" value="expense"><v-icon class="me-2">mdi-cash-minus</v-icon>Motivos de egreso</v-tab><v-tab v-if="canSeePurchases" value="voucher"><v-icon class="me-2">mdi-receipt-text-outline</v-icon>Comprobantes</v-tab></v-tabs><v-divider/><div class="pa-4 operaciones-toolbar"><v-text-field v-model="search" class="operaciones-search" placeholder="Buscar en el catálogo..." prepend-inner-icon="mdi-magnify" variant="outlined" density="comfortable" rounded="lg" hide-details clearable @keyup.enter="load"/><v-btn color="primary" variant="tonal" prepend-icon="mdi-magnify" @click="load">Buscar</v-btn><v-btn v-if="canManage" color="primary" prepend-icon="mdi-plus" rounded="lg" @click="openCreate">Nuevo</v-btn></div><v-divider/><div v-if="loading" class="text-center py-14"><v-progress-circular indeterminate color="primary"/></div><v-table v-else-if="items.length" hover class="operaciones-table"><thead><tr><th>ID</th><th>{{ tab==='voucher'?'Nombre':'Motivo' }}</th><th v-if="tab==='voucher'">Código SUNAT</th><th v-else>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody><tr v-for="item in items" :key="itemId(item)"><td>#{{ itemId(item) }}</td><td><strong>{{ itemName(item) }}</strong><v-chip v-if="isReserved(item)" size="x-small" color="info" variant="tonal" class="ms-2">Del sistema</v-chip></td><td v-if="isVoucher(item)">{{ item.codigoSunat||'—' }}</td><td v-else><v-chip size="small" :color="item.activo?'success':'error'" variant="tonal">{{ item.activo?'Activo':'Inactivo' }}</v-chip></td><td class="text-end"><v-btn v-if="canManage&&!isReserved(item)" icon="mdi-pencil-outline" variant="text" color="primary" @click="openEdit(item)"/><v-btn v-if="canManage&&!isReserved(item)" icon="mdi-delete-outline" variant="text" color="error" @click="confirmRemove(item)"/></td></tr></tbody></v-table><div v-else class="operaciones-empty"><v-icon size="48">mdi-format-list-bulleted</v-icon><div class="mt-2">No se encontraron registros</div></div></v-card>
    <v-dialog v-model="dialog" max-width="560" persistent><v-card rounded="xl"><v-card-title class="operaciones-dialog-title"><span class="operaciones-dialog-icon"><v-icon>mdi-pencil-outline</v-icon></span>{{ editing?'Editar':'Nuevo' }} registro<v-spacer/><v-btn icon="mdi-close" variant="text" color="on-primary" @click="dialog=false"/></v-card-title><v-card-text class="pa-5"><v-alert v-if="formError" type="error" variant="tonal" class="mb-4">{{ formError }}</v-alert><label class="operaciones-field-label">{{ tab==='voucher'?'Nombre':'Motivo' }} *</label><v-text-field v-model="form.name" variant="outlined" maxlength="100"/><template v-if="tab==='voucher'"><label class="operaciones-field-label">Código SUNAT (opcional)</label><v-text-field v-model="form.code" variant="outlined" maxlength="2" hint="Dos dígitos, por ejemplo 01" persistent-hint/></template><div v-else class="d-flex align-center justify-space-between"><div><strong>Estado</strong><div class="text-body-2 text-medium-emphasis">Disponible para nuevos movimientos</div></div><v-switch v-model="form.active" color="primary" hide-details/></div></v-card-text><v-card-actions class="pa-4"><v-spacer/><v-btn variant="text" @click="dialog=false">Cancelar</v-btn><v-btn color="primary" :loading="saving" @click="save">Guardar</v-btn></v-card-actions></v-card></v-dialog>
    <v-dialog v-model="deleteDialog" max-width="440"><v-card rounded="xl"><v-card-title>Eliminar registro</v-card-title><v-card-text>¿Eliminar <strong>{{ deleting?itemName(deleting):'' }}</strong>? Esta acción no se podrá realizar si ya está en uso.</v-card-text><v-card-actions><v-spacer/><v-btn variant="text" @click="deleteDialog=false">Cancelar</v-btn><v-btn color="error" :loading="saving" @click="remove">Eliminar</v-btn></v-card-actions></v-card></v-dialog><v-snackbar v-model="notice" color="success">Catálogo actualizado correctamente</v-snackbar>
  </div>
</template>
<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { getApiErrorMessage } from '@/core/api/api-error'
import { Permiso } from '@/core/constants/permisos'
import { useAuthStore } from '@/modules/auth/auth.store'
import { motivosEgresoApi, motivosIngresoApi, tiposComprobanteApi } from '../operaciones.api'
import type { MotivoEgreso, MotivoIngreso, TipoComprobante } from '../operaciones.types'
import '../operaciones.css'
type Item=MotivoIngreso|MotivoEgreso|TipoComprobante;type Tab='income'|'expense'|'voucher'
const auth=useAuthStore(),canSeeCash=computed(()=>auth.puede(Permiso.CAJA_VER)),canSeePurchases=computed(()=>auth.puede(Permiso.COMPRAS_VER)),tab=ref<Tab>(canSeeCash.value?'income':'voucher'),canManage=computed(()=>tab.value==='voucher'?auth.puede(Permiso.COMPRAS_GESTIONAR):auth.puede(Permiso.CAJA_GESTIONAR)),items=ref<Item[]>([]),editing=ref<Item|null>(null),deleting=ref<Item|null>(null),search=ref(''),loading=ref(false),saving=ref(false),dialog=ref(false),deleteDialog=ref(false),error=ref(''),formError=ref(''),notice=ref(false),form=reactive({name:'',code:'',active:true})
const api=computed(()=>tab.value==='income'?motivosIngresoApi:tab.value==='expense'?motivosEgresoApi:tiposComprobanteApi)
async function load(){loading.value=true;error.value='';try{const r=await api.value.listar({pagina:1,limite:100,buscar:search.value.trim()||undefined});items.value=r.data.data}catch(cause){error.value=getApiErrorMessage(cause,'No se pudo cargar el catálogo')}finally{loading.value=false}}
function openCreate(){editing.value=null;Object.assign(form,{name:'',code:'',active:true});formError.value='';dialog.value=true}function openEdit(item:Item){editing.value=item;Object.assign(form,{name:itemName(item),code:isVoucher(item)?item.codigoSunat??'':'',active:isVoucher(item)?true:item.activo});formError.value='';dialog.value=true}
async function save(){if(!form.name.trim()){formError.value='Ingresa un nombre';return}if(tab.value==='voucher'&&form.code&&!/^\d{2}$/.test(form.code)){formError.value='El código SUNAT debe tener dos dígitos';return}saving.value=true;try{const payload=tab.value==='voucher'?{nombre:form.name.trim(),codigoSunat:form.code||null}:{motivo:form.name.trim(),activo:form.active};if(editing.value)await api.value.actualizar(itemId(editing.value),payload);else await api.value.crear(payload);dialog.value=false;notice.value=true;await load()}catch(cause){formError.value=getApiErrorMessage(cause,'No se pudo guardar el registro')}finally{saving.value=false}}
function confirmRemove(item:Item){deleting.value=item;deleteDialog.value=true}async function remove(){if(!deleting.value)return;saving.value=true;try{await api.value.eliminar(itemId(deleting.value));deleteDialog.value=false;notice.value=true;await load()}catch(cause){deleteDialog.value=false;error.value=getApiErrorMessage(cause,'No se pudo eliminar el registro')}finally{saving.value=false}}
function isVoucher(item:Item):item is TipoComprobante{return'idTipoComprobante'in item}function itemId(item:Item){return'idTipoComprobante'in item?item.idTipoComprobante:'idMotivoIngreso'in item?item.idMotivoIngreso:item.idMotivoEgreso}function itemName(item:Item){return isVoucher(item)?item.nombre:item.motivo}function isReserved(item:Item){if(isVoucher(item))return false;return'idMotivoIngreso'in item?item.idMotivoIngreso<=2:item.idMotivoEgreso<=3}
watch(tab,load,{immediate:true})
</script>
