<template>
  <div class="operaciones-page">
    <v-card class="operaciones-header mb-5 rounded-xl" elevation="0" border><v-card-text class="pa-5"><div class="d-flex align-center flex-wrap ga-3"><v-avatar color="primary" variant="tonal" size="48" rounded="lg"><v-icon size="28">{{ isIncome?'mdi-cash-plus':'mdi-cash-minus' }}</v-icon></v-avatar><div><div class="text-h6 font-weight-bold">{{ title }}</div><div class="text-body-2 text-medium-emphasis">{{ isIncome?'Entradas de dinero registradas en caja':'Salidas de dinero registradas en caja' }}</div></div><v-spacer/><v-chip color="primary" variant="tonal">{{ branch.sucursalActual?.nombre||'Sin sucursal' }}</v-chip><v-btn v-if="canManage&&openBox" color="primary" prepend-icon="mdi-plus" rounded="lg" @click="openCreate">Nuevo {{ isIncome?'ingreso':'egreso' }}</v-btn></div></v-card-text></v-card>
    <v-alert v-if="error" type="error" variant="tonal" closable class="mb-4" @click:close="error=''">{{ error }}</v-alert><v-alert v-if="branch.idSucursalActual&&!openBox" type="warning" variant="tonal" class="mb-4">Debes abrir la caja de esta sucursal para registrar movimientos.</v-alert>
    <v-card rounded="xl" elevation="0" border class="overflow-hidden"><div class="pa-4 operaciones-toolbar"><v-text-field v-model="search" class="operaciones-search" placeholder="Buscar por detalle..." prepend-inner-icon="mdi-magnify" variant="outlined" density="comfortable" rounded="lg" clearable hide-details @keyup.enter="searchNow"/><v-select v-model="selectedReason" :items="reasonOptions" class="operaciones-filter" label="Motivo" variant="outlined" density="comfortable" rounded="lg" hide-details/><v-btn variant="tonal" color="primary" prepend-icon="mdi-filter" @click="searchNow">Filtrar</v-btn><v-btn icon="mdi-refresh" variant="tonal" color="primary" :loading="loading" @click="load"/></div><v-divider/><div v-if="loading" class="text-center py-14"><v-progress-circular indeterminate color="primary"/></div><template v-else-if="items.length"><v-table hover class="operaciones-table operaciones-desktop"><thead><tr><th>N.º</th><th>Fecha</th><th>Motivo</th><th>Detalle</th><th>Medios</th><th class="text-end">Monto</th><th></th></tr></thead><tbody><tr v-for="item in items" :key="idOf(item)"><td>#{{ idOf(item) }}</td><td>{{ dateTime(dateOf(item)) }}</td><td><v-chip size="small" color="primary" variant="tonal">{{ reasonOf(item) }}</v-chip></td><td>{{ item.detalle||'—' }}</td><td>{{ item.pagos.map(x=>x.medioPago.nombre).join(', ')||'Sin movimiento de caja' }}</td><td class="text-end font-weight-bold money" :class="isIncome?'text-success':'text-error'">{{ isIncome?'+':'-' }} {{ money(item.monto) }}</td><td><v-btn icon="mdi-eye-outline" variant="text" color="primary" @click="selected=item"/></td></tr></tbody></v-table><div class="operaciones-mobile pa-3"><v-card v-for="item in items" :key="idOf(item)" variant="outlined" rounded="lg" class="mb-3" @click="selected=item"><v-card-text><div class="d-flex"><strong>{{ reasonOf(item) }}</strong><v-spacer/><strong :class="isIncome?'text-success':'text-error'">{{ money(item.monto) }}</strong></div><div class="text-caption text-medium-emphasis mt-2">{{ dateTime(dateOf(item)) }} · {{ item.detalle||'Sin detalle' }}</div></v-card-text></v-card></div></template><div v-else class="operaciones-empty"><v-icon size="50">{{ isIncome?'mdi-cash-plus':'mdi-cash-minus' }}</v-icon><div class="mt-2">No se encontraron movimientos</div></div><v-divider/><div class="d-flex align-center justify-space-between pa-3"><span class="text-caption">Mostrando {{ items.length }} de {{ total }}</span><v-pagination v-if="total>limit" v-model="page" :length="Math.ceil(total/limit)" size="small"/></div></v-card>

    <v-dialog v-model="dialog" max-width="680" persistent><v-card rounded="xl"><v-card-title class="operaciones-dialog-title"><span class="operaciones-dialog-icon"><v-icon>{{ isIncome?'mdi-cash-plus':'mdi-cash-minus' }}</v-icon></span>Nuevo {{ isIncome?'ingreso':'egreso' }}<v-spacer/><v-btn icon="mdi-close" variant="text" color="on-primary" @click="dialog=false"/></v-card-title><v-card-text class="pa-5"><v-alert v-if="formError" type="error" variant="tonal" class="mb-4">{{ formError }}</v-alert><label class="operaciones-field-label">Motivo *</label><v-select v-model="form.reasonId" :items="reasons.filter(x=>x.activo&&!isSystemReason(x))" :item-title="reasonLabel" :item-value="reasonId" variant="outlined"/><v-row><v-col cols="12" sm="6"><label class="operaciones-field-label">Monto *</label><v-text-field v-model="form.amount" prefix="S/" type="number" min="0.01" step="0.01" variant="outlined"/></v-col><v-col cols="12" sm="6"><label class="operaciones-field-label">Fecha y hora</label><v-text-field v-model="form.date" type="datetime-local" variant="outlined"/></v-col></v-row><label class="operaciones-field-label">Detalle</label><v-textarea v-model="form.detail" rows="2" maxlength="500" variant="outlined"/><PagosEditor v-model="payments" :medios="paymentMethods"/></v-card-text><v-divider/><v-card-actions class="pa-4"><v-spacer/><v-btn variant="text" @click="dialog=false">Cancelar</v-btn><v-btn color="primary" :loading="saving" @click="save">Registrar</v-btn></v-card-actions></v-card></v-dialog>
    <v-dialog :model-value="!!selected" max-width="650" @update:model-value="selected=null"><v-card v-if="selected" rounded="xl"><v-card-title class="pa-5">Detalle del {{ isIncome?'ingreso':'egreso' }} #{{ idOf(selected) }}</v-card-title><v-card-text class="px-5 pb-5"><v-list lines="two"><v-list-item title="Fecha" :subtitle="dateTime(dateOf(selected))"/><v-list-item title="Motivo" :subtitle="reasonOf(selected)"/><v-list-item title="Detalle" :subtitle="selected.detalle||'Sin detalle'"/><v-list-item v-for="p in selected.pagos" :key="p.idMedioPago" :title="p.medioPago.nombre" :subtitle="money(p.monto)"/></v-list><v-divider/><div class="text-h6 text-end mt-4">Total: {{ money(selected.monto) }}</div></v-card-text><v-card-actions><v-spacer/><v-btn color="primary" variant="text" @click="selected=null">Cerrar</v-btn></v-card-actions></v-card></v-dialog><v-snackbar v-model="noticeVisible" color="success">Movimiento registrado correctamente</v-snackbar>
  </div>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { mediosPagoApi } from '@/core/api/administracion.api'
import { getApiErrorMessage } from '@/core/api/api-error'
import { Permiso } from '@/core/constants/permisos'
import type { MedioPago } from '@/core/types/administracion.types'
import { useAuthStore } from '@/modules/auth/auth.store'
import { useSucursalStore } from '@/shared/stores/sucursal.store'
import PagosEditor from '../components/PagosEditor.vue'
import { cajasApi, cargarTodo, egresosApi, ingresosApi, motivosEgresoApi, motivosIngresoApi } from '../operaciones.api'
import type { Caja, MotivoEgreso, MotivoIngreso, Movimiento, PagoPayload } from '../operaciones.types'
import '../operaciones.css'
import { useRegistroDesdeCaja } from '../useRegistroDesdeCaja'
const route=useRoute(),auth=useAuthStore(),branch=useSucursalStore(),isIncome=computed(()=>route.name==='operaciones-ingresos'),title=computed(()=>isIncome.value?'Ingresos':'Egresos'),canManage=computed(()=>auth.puede(Permiso.CAJA_GESTIONAR))
const items=ref<Movimiento[]>([]),reasons=ref<Array<MotivoIngreso|MotivoEgreso>>([]),paymentMethods=ref<MedioPago[]>([]),openBox=ref<Caja|null>(null),selected=ref<Movimiento|null>(null),search=ref(''),selectedReason=ref<number|null>(null),page=ref(1),limit=30,total=ref(0),loading=ref(false),saving=ref(false),dialog=ref(false),error=ref(''),formError=ref(''),noticeVisible=ref(false),payments=ref<PagoPayload[]>([]),form=reactive({reasonId:null as number|null,amount:'',date:'',detail:''})
const reasonOptions=computed(()=>[{title:'Todos los motivos',value:null},...reasons.value.map(x=>({title:reasonLabel(x),value:reasonId(x)}))])
let loadRequest = 0
async function load(){
  const idSucursal=branch.idSucursalActual,current=++loadRequest,income=isIncome.value
  if(!idSucursal){items.value=[];total.value=0;openBox.value=null;loading.value=false;return}
  loading.value=true;error.value='';openBox.value=null
  try{
    const api=income?ingresosApi:egresosApi
    const [catalogData,list,methods,box]=await Promise.all([
      income?cargarTodo(motivosIngresoApi.listar,{activo:true}):cargarTodo(motivosEgresoApi.listar,{activo:true}),
      api.listar({idSucursal,pagina:page.value,limite:limit,buscar:search.value.trim()||undefined,...(income?{idMotivoIngreso:selectedReason.value??undefined}:{idMotivoEgreso:selectedReason.value??undefined})}),
      mediosPagoApi.listar(),cajasApi.abierta(idSucursal).catch(()=>null),
    ])
    if(current!==loadRequest)return
    items.value=list.data.data;total.value=list.data.total;reasons.value=catalogData.filter(item=>!isSystemReason(item));paymentMethods.value=methods.data;openBox.value=box?.data??null
  }catch(cause){if(current===loadRequest)error.value=getApiErrorMessage(cause,'No se pudieron cargar los movimientos')}
  finally{if(current===loadRequest)loading.value=false}
}
function searchNow(){if(page.value!==1)page.value=1;else void load()}
function openCreate(){Object.assign(form,{reasonId:null,amount:'',date:'',detail:''});payments.value=[];formError.value='';dialog.value=true}
async function save(){if(saving.value)return;if(!openBox.value||!branch.idSucursalActual||!form.reasonId){formError.value='Selecciona un motivo';return}const amount=Number(form.amount);const paid=payments.value.reduce((s,x)=>s+Number(x.monto||0),0);if(!(amount>0)){formError.value='Ingresa un monto válido';return}if(Math.abs(amount-paid)>.001){formError.value='La suma de los pagos debe coincidir con el monto';return}saving.value=true;try{const common={idCaja:openBox.value.idCaja,idSucursal:branch.idSucursalActual,monto:amount.toFixed(2),detalle:form.detail.trim()||undefined,pagos:payments.value};if(isIncome.value)await ingresosApi.crear({...common,idMotivoIngreso:form.reasonId,fechaIngreso:toIso(form.date)});else await egresosApi.crear({...common,idMotivoEgreso:form.reasonId,fechaEgreso:toIso(form.date)});dialog.value=false;noticeVisible.value=true;await load()}catch(cause){formError.value=getApiErrorMessage(cause,'No se pudo registrar el movimiento')}finally{saving.value=false}}
function reasonId(item:MotivoIngreso|MotivoEgreso){return 'idMotivoIngreso'in item?item.idMotivoIngreso:item.idMotivoEgreso}function reasonLabel(item:MotivoIngreso|MotivoEgreso){return item.motivo}function idOf(item:Movimiento){return 'idIngreso'in item?item.idIngreso:item.idEgreso}function dateOf(item:Movimiento){return 'fechaIngreso'in item?item.fechaIngreso:item.fechaEgreso}function reasonOf(item:Movimiento){return 'motivoIngreso'in item?item.motivoIngreso.motivo:item.motivoEgreso.motivo}
function isSystemReason(item:MotivoIngreso|MotivoEgreso){return 'idMotivoIngreso'in item?item.idMotivoIngreso<=2:item.idMotivoEgreso<=3}
function toIso(value:string){return value?new Date(value).toISOString():undefined}function money(v:string|number){return new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(v)||0)}function dateTime(v:string){return new Intl.DateTimeFormat('es-PE',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}
watch([()=>branch.idSucursalActual,page,()=>route.name],()=>void load(),{immediate:true})
watch([()=>branch.idSucursalActual,()=>route.name],()=>{dialog.value=false;selected.value=null;selectedReason.value=null;page.value=1})
onBeforeUnmount(()=>{loadRequest++})
useRegistroDesdeCaja(openBox,loading,canManage,error,openCreate)
</script>
