export const MOTIVO_INGRESO_VENTA = 1;
export const MOTIVO_INGRESO_ABONO_DEUDA = 2;

export const MOTIVO_EGRESO_COMPRA = 1;
export const MOTIVO_EGRESO_PERCEPCION = 2;
export const MOTIVO_EGRESO_CREDITO_CLIENTE = 3;

export const MEDIO_PAGO_FRACCIONADO = 'Fraccionado';

export const MOTIVOS_INGRESO_SISTEMA = new Set([
  MOTIVO_INGRESO_VENTA,
  MOTIVO_INGRESO_ABONO_DEUDA,
]);

export const MOTIVOS_EGRESO_SISTEMA = new Set([
  MOTIVO_EGRESO_COMPRA,
  MOTIVO_EGRESO_PERCEPCION,
  MOTIVO_EGRESO_CREDITO_CLIENTE,
]);
