<template>
  <div class="logistica-page">
    <v-card class="mb-5 rounded-xl" elevation="0" border><v-card-text class="pa-4"><div class="d-flex align-center flex-wrap ga-3 mb-4"><v-icon icon="mdi-warehouse" color="primary" size="28"/><div class="text-h6 font-weight-bold">Almacenes</div><v-chip color="primary" variant="tonal" size="small">{{ branch.sucursalActual?.nombre || 'Sin sucursal' }}</v-chip><v-spacer/><v-btn v-if="canManage && branch.idSucursalActual" color="primary" prepend-icon="mdi-plus" rounded="lg" @click="openCreate">Nuevo almacén</v-btn></div><div class="logistica-toolbar"><v-text-field v-model="search" class="logistica-search" placeholder="Buscar almacén..." prepend-inner-icon="mdi-magnify" variant="outlined" density="comfortable" rounded="lg" clearable hide-details @update:model-value="scheduleSearch" @keyup.enter="searchNow"/><v-select v-model="status" class="logistica-filter" :items="['Todos','Activos','Inactivos']" label="Estado" variant="outlined" density="comfortable" rounded="lg" hide-details/><v-btn icon="mdi-refresh" color="primary" variant="tonal" rounded="lg" :loading="loading" aria-label="Actualizar almacenes" @click="load"/><span class="logistica-count"><v-icon size="19">mdi-warehouse</v-icon>{{ total }} almacenes</span></div></v-card-text></v-card>
    <v-alert v-if="error" type="error" variant="tonal" closable class="mb-4" @click:close="error = ''">{{ error }}</v-alert>
    <v-alert v-if="!branch.idSucursalActual" type="info" variant="tonal" class="mb-4">Selecciona una sucursal para ver sus almacenes.</v-alert>
    <v-card rounded="xl" elevation="0" border class="overflow-hidden"><div v-if="loading" class="text-center py-14"><v-progress-circular indeterminate color="primary"/></div><template v-else-if="items.length"><v-table hover class="logistica-table logistica-desktop"><thead><tr><th>ID</th><th>Almacén</th><th>Dirección</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody><tr v-for="item in items" :key="item.idAlmacen"><td>#{{ item.idAlmacen }}</td><td><div class="d-flex align-center ga-3"><v-avatar color="primary" variant="tonal" size="36"><v-icon icon="mdi-warehouse"/></v-avatar><strong>{{ item.nombre }}</strong></div></td><td>{{ item.direccion || '—' }}</td><td><v-chip size="small" :color="item.estado ? 'success' : 'error'" variant="tonal">{{ item.estado ? 'Activo' : 'Inactivo' }}</v-chip></td><td class="text-end"><v-btn v-if="canManage" icon="mdi-pencil-outline" size="small" variant="text" color="primary" :aria-label="`Editar ${item.nombre}`" @click="openEdit(item)"/><v-btn v-if="canManage" icon="mdi-delete-outline" size="small" variant="text" color="error" :aria-label="`Eliminar ${item.nombre}`" @click="confirmDelete(item)"/></td></tr></tbody></v-table><div class="logistica-mobile pa-3"><v-card v-for="item in items" :key="item.idAlmacen" variant="outlined" rounded="lg" class="mb-3"><v-card-text class="pa-3"><div class="d-flex align-center ga-3"><v-avatar color="primary" variant="tonal"><v-icon icon="mdi-warehouse"/></v-avatar><div class="flex-grow-1"><strong>{{ item.nombre }}</strong><div class="text-caption text-medium-emphasis">{{ item.direccion || 'Sin dirección' }}</div></div><v-chip size="x-small" :color="item.estado ? 'success' : 'error'" variant="tonal">{{ item.estado ? 'Activo' : 'Inactivo' }}</v-chip></div><div v-if="canManage" class="d-flex justify-end mt-2"><v-btn size="small" variant="text" color="primary" @click="openEdit(item)">Editar</v-btn><v-btn size="small" variant="text" color="error" @click="confirmDelete(item)">Eliminar</v-btn></div></v-card-text></v-card></div></template><div v-else class="logistica-empty"><v-icon icon="mdi-warehouse" size="48" class="mb-3"/><div>No se encontraron almacenes</div></div><v-divider/><div class="d-flex align-center justify-space-between pa-3"><span class="text-caption text-medium-emphasis">Mostrando {{ items.length }} de {{ total }}</span><v-pagination v-if="total > limit" v-model="page" :length="Math.ceil(total / limit)" :total-visible="5" size="small" color="primary"/></div></v-card>
    <v-dialog v-model="dialog" max-width="600" persistent><v-card rounded="xl" class="overflow-hidden"><v-card-title class="logistica-dialog-title"><span class="logistica-dialog-icon"><v-icon icon="mdi-warehouse"/></span>{{ editing ? 'Editar almacén' : 'Nuevo almacén' }}<v-spacer/><v-btn icon="mdi-close" variant="text" color="on-primary" @click="dialog = false"/></v-card-title><v-card-text class="pa-5"><v-alert v-if="formError" type="error" variant="tonal" class="mb-4">{{ formError }}</v-alert><div class="text-body-2 text-medium-emphasis mb-4">Sucursal: {{ branch.sucursalActual?.nombre }}</div><label class="logistica-field-label">Nombre *</label><v-text-field v-model="form.nombre" placeholder="Ej.: Almacén principal" variant="outlined" density="comfortable" maxlength="150"/><label class="logistica-field-label">Dirección (opcional)</label><v-text-field v-model="form.direccion" placeholder="Ubicación del almacén" variant="outlined" density="comfortable" maxlength="300"/><v-divider class="my-3"/><div class="d-flex align-center justify-space-between"><div><div class="font-weight-bold">Estado</div><div class="text-body-2 text-medium-emphasis">Disponible para registrar inventario.</div></div><v-switch v-model="form.estado" color="primary" hide-details/></div></v-card-text><v-divider/><v-card-actions class="pa-4"><v-spacer/><v-btn variant="text" @click="dialog = false">Cancelar</v-btn><v-btn color="primary" :loading="saving" @click="save">{{ editing ? 'Actualizar' : 'Guardar' }}</v-btn></v-card-actions></v-card></v-dialog>
    <v-dialog v-model="deleteDialog" max-width="440"><v-card rounded="xl"><v-card-title>Eliminar almacén</v-card-title><v-card-text>¿Eliminar <strong>{{ deleting?.nombre }}</strong>? Si tiene existencias, desactívalo en su lugar.</v-card-text><v-card-actions><v-spacer/><v-btn variant="text" @click="deleteDialog = false">Cancelar</v-btn><v-btn color="error" :loading="saving" @click="remove">Eliminar</v-btn></v-card-actions></v-card></v-dialog><v-snackbar v-model="noticeVisible" color="success">{{ notice }}</v-snackbar>
  </div>
</template>
<script setup lang="ts">
import { computed, onUnmounted, reactive, ref, watch } from 'vue'
import { getApiErrorMessage } from '@/core/api/api-error'
import { Permiso } from '@/core/constants/permisos'
import { useAuthStore } from '@/modules/auth/auth.store'
import { useSucursalStore } from '@/shared/stores/sucursal.store'
import { almacenesApi } from '../logistica.api'
import type { Almacen } from '../logistica.types'
import '../logistica.css'
const auth=useAuthStore(), branch=useSucursalStore(), canManage=computed(()=>auth.puede(Permiso.LOGISTICA_GESTIONAR))
const items=ref<Almacen[]>([]), search=ref(''), status=ref('Todos'), page=ref(1), limit=50, total=ref(0)
const loading=ref(false), saving=ref(false), dialog=ref(false), deleteDialog=ref(false), editing=ref<Almacen|null>(null), deleting=ref<Almacen|null>(null)
const error=ref(''), formError=ref(''), notice=ref(''), noticeVisible=ref(false), form=reactive({nombre:'',direccion:'',estado:true})
let timer:ReturnType<typeof setTimeout>|undefined, requestId=0
async function load(){const current=++requestId;if(!branch.idSucursalActual){items.value=[];total.value=0;return}loading.value=true;error.value='';try{const {data}=await almacenesApi.listar({pagina:page.value,limite:limit,idSucursal:branch.idSucursalActual,buscar:search.value.trim()||undefined,estado:status.value==='Todos'?undefined:status.value==='Activos'});if(current===requestId){items.value=data.data;total.value=data.total}}catch(cause){if(current===requestId)error.value=getApiErrorMessage(cause,'No se pudieron cargar los almacenes')}finally{if(current===requestId)loading.value=false}}
function searchNow(){if(timer)clearTimeout(timer);if(page.value!==1)page.value=1;else void load()}
function scheduleSearch(){if(timer)clearTimeout(timer);timer=setTimeout(searchNow,350)}
function openCreate(){editing.value=null;Object.assign(form,{nombre:'',direccion:'',estado:true});formError.value='';dialog.value=true}
function openEdit(item:Almacen){editing.value=item;Object.assign(form,{nombre:item.nombre,direccion:item.direccion??'',estado:item.estado});formError.value='';dialog.value=true}
async function save(){if(!form.nombre.trim()){formError.value='Ingresa el nombre del almacén';return}if(!branch.idSucursalActual)return;saving.value=true;formError.value='';try{const payload={nombre:form.nombre.trim(),direccion:form.direccion.trim()||null,estado:form.estado};if(editing.value)await almacenesApi.actualizar(editing.value.idAlmacen,payload);else await almacenesApi.crear({...payload,idSucursal:branch.idSucursalActual});dialog.value=false;notice.value='Almacén guardado';noticeVisible.value=true;await load()}catch(cause){formError.value=getApiErrorMessage(cause,'No se pudo guardar el almacén')}finally{saving.value=false}}
function confirmDelete(item:Almacen){deleting.value=item;deleteDialog.value=true}
async function remove(){if(!deleting.value)return;saving.value=true;error.value='';try{await almacenesApi.eliminar(deleting.value.idAlmacen);deleteDialog.value=false;notice.value='Almacén eliminado';noticeVisible.value=true;await load()}catch(cause){deleteDialog.value=false;error.value=getApiErrorMessage(cause,'No se pudo eliminar el almacén')}finally{saving.value=false}}
watch([()=>branch.idSucursalActual,status],()=>{if(page.value!==1)page.value=1;else void load()});watch(page,load,{immediate:true});onUnmounted(()=>{if(timer)clearTimeout(timer);requestId++})
</script>
