export const Permiso = {
  USUARIOS_VER: 'USUARIOS_VER',
  USUARIOS_CREAR: 'USUARIOS_CREAR',
  USUARIOS_EDITAR: 'USUARIOS_EDITAR',
  USUARIOS_ELIMINAR: 'USUARIOS_ELIMINAR',
  USUARIOS_ACTIVAR: 'USUARIOS_ACTIVAR',
  DOCUMENTOS_CONSULTAR: 'DOCUMENTOS_CONSULTAR',
  ROLES_VER: 'ROLES_VER',
  ROLES_CREAR: 'ROLES_CREAR',
  ROLES_EDITAR: 'ROLES_EDITAR',
  PERMISOS_VER: 'PERMISOS_VER',
  PERMISOS_ASIGNAR: 'PERMISOS_ASIGNAR',
  SUCURSALES_VER: 'SUCURSALES_VER',
  SUCURSALES_CREAR: 'SUCURSALES_CREAR',
  SUCURSALES_EDITAR: 'SUCURSALES_EDITAR',
} as const

export type Permiso = (typeof Permiso)[keyof typeof Permiso]

export const RolSistema = {
  SUPERADMIN: 'SUPERADMIN',
} as const
