export const Permiso = {
  USUARIOS_VER: 'USUARIOS_VER',
  USUARIOS_CREAR: 'USUARIOS_CREAR',
  USUARIOS_EDITAR: 'USUARIOS_EDITAR',
  USUARIOS_ACTIVAR: 'USUARIOS_ACTIVAR',
  USUARIOS_DESACTIVAR: 'USUARIOS_DESACTIVAR',
  USUARIOS_ASIGNAR_SUCURSALES: 'USUARIOS_ASIGNAR_SUCURSALES',
  ROLES_VER: 'ROLES_VER',
  ROLES_CREAR: 'ROLES_CREAR',
  ROLES_EDITAR: 'ROLES_EDITAR',
  PERMISOS_VER: 'PERMISOS_VER',
  PERMISOS_ASIGNAR: 'PERMISOS_ASIGNAR',
  SUCURSALES_VER: 'SUCURSALES_VER',
  SUCURSALES_CREAR: 'SUCURSALES_CREAR',
  SUCURSALES_EDITAR: 'SUCURSALES_EDITAR',
  SUCURSALES_ACTIVAR: 'SUCURSALES_ACTIVAR',
  SUCURSALES_DESACTIVAR: 'SUCURSALES_DESACTIVAR',
  MEDIOS_PAGO_VER: 'MEDIOS_PAGO_VER',
  MEDIOS_PAGO_CREAR: 'MEDIOS_PAGO_CREAR',
  MEDIOS_PAGO_EDITAR: 'MEDIOS_PAGO_EDITAR',
  MEDIOS_PAGO_ELIMINAR: 'MEDIOS_PAGO_ELIMINAR',
} as const

export type Permiso = (typeof Permiso)[keyof typeof Permiso]

export const RolSistema = {
  SUPERADMIN: 'SUPERADMIN',
} as const
