export const Permiso = {
  USUARIOS_VER: 'USUARIOS_VER',
  USUARIOS_GESTIONAR: 'USUARIOS_GESTIONAR',
  SUCURSALES_VER: 'SUCURSALES_VER',
  SUCURSALES_GESTIONAR: 'SUCURSALES_GESTIONAR',
  MEDIOS_PAGO_VER: 'MEDIOS_PAGO_VER',
  MEDIOS_PAGO_GESTIONAR: 'MEDIOS_PAGO_GESTIONAR',
  PERSONAS_VER: 'PERSONAS_VER',
  PERSONAS_GESTIONAR: 'PERSONAS_GESTIONAR',
  LOGISTICA_VER: 'LOGISTICA_VER',
  LOGISTICA_GESTIONAR: 'LOGISTICA_GESTIONAR',
  CAJA_VER: 'CAJA_VER',
  CAJA_GESTIONAR: 'CAJA_GESTIONAR',
  VENTAS_VER: 'VENTAS_VER',
  VENTAS_GESTIONAR: 'VENTAS_GESTIONAR',
  COMPRAS_VER: 'COMPRAS_VER',
  COMPRAS_GESTIONAR: 'COMPRAS_GESTIONAR',
  DEUDAS_VER: 'DEUDAS_VER',
  DEUDAS_GESTIONAR: 'DEUDAS_GESTIONAR',
} as const

export type Permiso = (typeof Permiso)[keyof typeof Permiso]

export const RolSistema = {
  SUPERADMIN: 'SUPERADMIN',
} as const
